version: '3'

services:

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.16
    container_name: redis-wsbe
    env_file: .env
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "6379:6379"
    restart: unless-stopped

  nats:
    image: nats:alpine3.17
    container_name: nats-main
    env_file:
      - .env
    environment:
      NATS_SERVERS: ${NATS_SERVERS}
      NATS_USERNAME: ${NATS_USERNAME}
      NATS_PASSWORD: ${NATS_PASSWORD}
    command: "--js -m 8009"
    volumes:
      - ./data:/data
    ports:
      - "4222:${NATS_PORT}"
      - "8009:8009"

volumes:
  minio_storage:
  postgres-data:
  redis:
  nats:

